query getAmenityTypes($input: GetAmenityTypesInput!) {
  getAmenityTypes(input: $input) {
    page
    total
    totalPages
    message
    items {
      id
      name
      description
      isActive
      createdAt
      updatedAt
    }
  }
}
