query getAmenityType($id: Float!) {
  getAmenityType(id: $id) {
    message
    amenityType {
      id
      name
      icon
      isActive
      description
      createdAt
      updatedAt
    }
  }
}
