query getLocation($id: Float!) {
  getLocation(id: $id) {
    message
    location {
      id
      name
      address
      long
      lat
      images
      thumbnail
      description
      numOfFloor
      income
      isActive
      minPrice
      createdAt
      electricCounterPrice
      locationServices {
        id
        name
        description
      }
      contactInformations {
        address
        name
        id
        phoneNumber
        email
      }
    }
  }
}
