query getLocations($input: GetLocationsInput!) {
  getLocations(input: $input) {
    page
    total
    totalPages
    message
    items {
      id
      name
      address
      long
      lat
      images
      thumbnail
      description
      numOfFloor
      income
      isActive
      createdAt
    }
  }
}
