query getUsers($input: GetUsersInput!) {
  getUsers(input: $input) {
    page
    total
    totalPages
    message
    items {
      id
      name
      email
      address
      phoneNumber
      dateOfBirth
      identityNumber
      avatar
      isActive
      room {
        name
      }
      roomId
      createdAt
    }
  }
}
